run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - examples

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - gocritic
    - goimports
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: examples/
      linters:
        - errcheck