run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - gocritic
    - goimports
    - revive

linters-settings:
  gocyclo:
    min-complexity: 55  # High threshold for VTE parser state machines
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  revive:
    rules:
      - name: unused-parameter
        disabled: true  # Disabled for interface implementations
  gosec:
    excludes:
      - G115  # Integer overflow - we handle these cases properly

issues:
  exclude-dirs:
    - vendor
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocyclo
    - path: examples/
      linters:
        - errcheck
    - path: performer\.go
      linters:
        - revive
      text: "unused-parameter"
    - path: handler\.go
      linters:
        - revive
      text: "unused-parameter"